name: "Reusable Python CI workflow"

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        type: string
        default: '3.11'
      working-directory:
        description: 'Directory where the code is located'
        required: false
        type: string
        default: '.'
      test-command:
        description: 'Command to run the tests'
        required: false
        type: string
        default: 'pytest --maxfail=1'
      dependency-install-command:
        description: 'Command to install dependencies'
        required: false
        type: string
        default: 'pip install -r requirements.txt'
      sonar-project-key:
        description: 'SonarQube project key'
        required: true
        type: string
    secrets:
      sonar-token:
        description: 'SonarQube token for authentication'
        required: true

jobs:

  python-CI-Unit-Tests:
    name: Python CI - Unit Tests
    runs-on: Linux
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ${{ inputs.dependency-install-command }}
      - name: Run tests
        run: ${{ inputs.test-command }}

  sonarqube-scan:
    needs: python-CI-Unit-Tests
    name: SonarQube Scan
    runs-on: Linux
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          skipSignatureVerification: true

        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
