on:
  workflow_call:

    inputs:
      sonar-project-key:
        description: 'SonarQube project key'
        required: true
        type: string
      coverage-artifact-name:
        description: 'Name of the coverage artifact to upload'
        required: false
        type: string
        default: 'coverage-report'

    secrets:
      sonar-token:
        description: 'SonarQube token for authentication'
        required: true


jobs:

  sonarqube-scan:
    name: SonarQube Scan
    runs-on: Linux

    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.coverage-artifact-name }}
          path: .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
          skipSignatureVerification: true
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}

      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}

      - name: "Show Quality Gate Status"
        run: |
          echo Quality Gate Status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}
