on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory where the code is located'
        required: false
        type: string
        default: '.'
      plan-artifact-name:
        description: 'Name of the Terraform plan artifact to upload'
        required: false
        type: string
        default: 'terraform-plan-${{ vars.AWS_ACCOUNT_ID }}'
      plan-artifact-path:
        description: 'Path where the Terraform plan artifact will be stored'
        required: false
        type: string
        default: 'tfplans'
      environment:
        description: 'Environment name'
        required: true
        type: string
      aws-account-id:
        description: 'AWS Account ID'
        required: true
        type: string
      aws-region:
        description: 'AWS Region'
        type: string
        required: false
        default: 'eu-west-1'
    secrets:
      aws-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret:
        description: 'AWS Secret'

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: Linux
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-id }}
          aws-secret-access-key: ${{ secrets.aws-secret }}
          aws-region: ${{ inputs.aws-region }}   # o la región que uses

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=${ inputs.environment }.tfvars -out=${ inputs.plan-artifact-name }

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.plan-artifact-name }}
          path: ${ inputs.plan-artifact-path }/${ inputs.plan-artifact-name }
          retention-days: 7
