on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory where the code is located'
        required: false
        type: string
        default: '.'
      plan-artifact-name:
        description: 'Name of the Terraform plan artifact to upload'
        required: false
        type: string
        default: 'terraform-plan'
      plan-artifact-path:
        description: 'Path where the Terraform plan artifact will be stored'
        required: false
        type: string
        default: 'tfplans'
      environment:
        description: 'Environment name'
        required: true
        type: string
      aws-account-id:
        description: 'AWS Account ID'
        required: true
        type: string
      aws-region:
        description: 'AWS Region'
        type: string
        required: false
        default: 'eu-west-1'
    secrets:
      aws-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret:
        description: 'AWS Secret'

jobs:

  terraform-plan:
    name: Terraform Apply
    runs-on: Linux
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.7  # o la región que uses

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}

      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: "${{ inputs.plan-artifact-name }}-${{ inputs.aws-account-id }}-${{ inputs.environment }}.tfplan"
          path: .

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve "${{ inputs.plan-artifact-name }}-${{ inputs.aws-account-id }}-${{ inputs.environment }}.tfplan"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
